apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatinfra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatinfra
  template:
    metadata:
      labels:
        app: tomcatinfra
    spec:
      containers:
      - image: sampleappln.azurecr.io/github-saravanan/demo1:39
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: tomcatinfra
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
